/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ui;

import curriculum.NewCurriculum;
import ui.programs.NewFieldOfStudy;
import ui.programs.NewProgramAdmission;
import ui.programs.NewProgramAward;
import ui.programs.NewProgramStudy;

/**
 *
 * @author ChalewT
 */
public class JSimsMain extends javax.swing.JFrame {

    /**
     * Creates new form JSimsMain
     */
    public JSimsMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        mnuOrganization = new javax.swing.JMenu();
        mnuiNewCollege = new javax.swing.JMenuItem();
        mnuiNewDepartment = new javax.swing.JMenuItem();
        mnuiViewColleges = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuiNewFieldOfStudy = new javax.swing.JMenuItem();
        mnuProgramAward = new javax.swing.JMenuItem();
        mnuProgramAdmission = new javax.swing.JMenuItem();
        mnuProgramStudy = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuNewCurriculum = new javax.swing.JMenuItem();
        mnuViewCurriculla = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuAvailableProgram = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuAdmitStudent = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAcademicYear = new javax.swing.JMenuItem();
        mnuAcademicSemester = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JSims - Student Information Management System");
        setExtendedState(MAXIMIZED_BOTH);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        mnuOrganization.setMnemonic('I');
        mnuOrganization.setText("Institution");

        mnuiNewCollege.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiNewCollege.setText("New College");
        mnuiNewCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNewCollegeActionPerformed(evt);
            }
        });
        mnuOrganization.add(mnuiNewCollege);

        mnuiNewDepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuiNewDepartment.setText("New Department");
        mnuiNewDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNewDepartmentActionPerformed(evt);
            }
        });
        mnuOrganization.add(mnuiNewDepartment);

        mnuiViewColleges.setText("View Colleges");
        mnuiViewColleges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiViewCollegesActionPerformed(evt);
            }
        });
        mnuOrganization.add(mnuiViewColleges);

        menuBar.add(mnuOrganization);

        jMenu1.setMnemonic('P');
        jMenu1.setText("Program");

        mnuiNewFieldOfStudy.setText("Field of Study");
        mnuiNewFieldOfStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNewFieldOfStudyActionPerformed(evt);
            }
        });
        jMenu1.add(mnuiNewFieldOfStudy);

        mnuProgramAward.setText("Program Award");
        mnuProgramAward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramAwardActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProgramAward);

        mnuProgramAdmission.setText("Program Admission");
        mnuProgramAdmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramAdmissionActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProgramAdmission);

        mnuProgramStudy.setText("Program Study");
        mnuProgramStudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProgramStudyActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProgramStudy);

        menuBar.add(jMenu1);

        jMenu2.setText("Curriculum");

        mnuNewCurriculum.setText("New Curriculum");
        mnuNewCurriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewCurriculumActionPerformed(evt);
            }
        });
        jMenu2.add(mnuNewCurriculum);

        mnuViewCurriculla.setText("View Curricula");
        mnuViewCurriculla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewCurricullaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuViewCurriculla);

        jMenuItem2.setText("Course");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        menuBar.add(jMenu2);

        mnuAvailableProgram.setText("Admission");

        jMenuItem1.setText("Available Programs");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAvailableProgram.add(jMenuItem1);

        mnuAdmitStudent.setText("Admit Student");
        mnuAdmitStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdmitStudentActionPerformed(evt);
            }
        });
        mnuAvailableProgram.add(mnuAdmitStudent);

        menuBar.add(mnuAvailableProgram);

        jMenu3.setText("Ac Calender");

        mnuAcademicYear.setText("Academic Year");
        mnuAcademicYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcademicYearActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAcademicYear);

        mnuAcademicSemester.setText("Academic Semester");
        jMenu3.add(mnuAcademicSemester);

        menuBar.add(jMenu3);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(817, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuiNewCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNewCollegeActionPerformed
        NewCollege college = new NewCollege(this, true);
        college.setLocationRelativeTo(this);
        college.setVisible(true);
    }//GEN-LAST:event_mnuiNewCollegeActionPerformed

    private void mnuiNewDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNewDepartmentActionPerformed
        // TODO add your handling code here:
        NewDepartment dept = new NewDepartment(this, true);
        dept.setLocationRelativeTo(this);
        dept.setVisible(true);
    }//GEN-LAST:event_mnuiNewDepartmentActionPerformed

    private void mnuiViewCollegesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiViewCollegesActionPerformed
        ViewCollege faculty = new ViewCollege();
        desktopPane.add(faculty);
        faculty.setVisible(true);
        faculty.toFront();
    }//GEN-LAST:event_mnuiViewCollegesActionPerformed

    private void mnuiNewFieldOfStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNewFieldOfStudyActionPerformed
        NewFieldOfStudy field = new NewFieldOfStudy(this, true);
        field.setLocationRelativeTo(this);
        field.setVisible(true);
    }//GEN-LAST:event_mnuiNewFieldOfStudyActionPerformed

    private void mnuProgramAwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramAwardActionPerformed
        NewProgramAward form = new NewProgramAward(this, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_mnuProgramAwardActionPerformed

    private void mnuProgramAdmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramAdmissionActionPerformed
        NewProgramAdmission form = new NewProgramAdmission(this, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_mnuProgramAdmissionActionPerformed

    private void mnuProgramStudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProgramStudyActionPerformed
        NewProgramStudy form = new NewProgramStudy(this, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_mnuProgramStudyActionPerformed

    private void mnuNewCurriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewCurriculumActionPerformed
        NewCurriculum form = new NewCurriculum(this, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);
    }//GEN-LAST:event_mnuNewCurriculumActionPerformed

    private void mnuViewCurricullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewCurricullaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuViewCurricullaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuAdmitStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdmitStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAdmitStudentActionPerformed

    private void mnuAcademicYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcademicYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAcademicYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSimsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSimsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSimsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSimsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSimsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAcademicSemester;
    private javax.swing.JMenuItem mnuAcademicYear;
    private javax.swing.JMenuItem mnuAdmitStudent;
    private javax.swing.JMenu mnuAvailableProgram;
    private javax.swing.JMenuItem mnuNewCurriculum;
    private javax.swing.JMenu mnuOrganization;
    private javax.swing.JMenuItem mnuProgramAdmission;
    private javax.swing.JMenuItem mnuProgramAward;
    private javax.swing.JMenuItem mnuProgramStudy;
    private javax.swing.JMenuItem mnuViewCurriculla;
    private javax.swing.JMenuItem mnuiNewCollege;
    private javax.swing.JMenuItem mnuiNewDepartment;
    private javax.swing.JMenuItem mnuiNewFieldOfStudy;
    private javax.swing.JMenuItem mnuiViewColleges;
    // End of variables declaration//GEN-END:variables

}
